apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: skril/moscow-time:python
          ports:
            - containerPort: 8080
